### ISSUE TITLE
Perform a 0.5 Beta release QC check.

### ISSUE THREAD

**Issue by MrFarland** [MrFarland/DM-Operations-Center#37]
Check every menu link works in the 1st and 2nd level menus for:
- [x] Abilities
- [x] Campaign
- [x] Character
- [x] Combat
- [x] Conditions
- [x] Downtime
- [x] Encounters
- [x] Environment
- [x] Equipment
- [x] Expenses
- [x] Life & Death
- [x] Movement
- [x] Spellcasting
- [x] Treasure
- [x] Worldbuilding

Check the breadcrumb links on no less than five pages in each section:
- [x] Abilities
- [x] Campaign
- [x] Character
- [x] Combat
- [x] Conditions
- [x] Downtime
- [x] Encounters
- [x] Environment
- [x] Equipment
- [x] Expenses
- [x] Life & Death
- [x] Movement
- [x] Spellcasting
- [x] Treasure
- [x] Worldbuilding

Check all links out of a given page in each section:
- [x] Abilities
- [x] Campaign
- [x] Character
- [x] Combat
- [x] Conditions
- [x] Downtime
- [x] Encounters
- [x] Environment
- [x] Equipment
- [x] Expenses
- [x] Life & Death
- [x] Movement
- [x] Spellcasting
- [x] Treasure
- [x] Worldbuilding

**Comment by TheCrazySpy** [comment]
I'm happy to help test, if you'd like. It will take me a little while, I only have a few hours a day to do fun stuff like this. 

Here's my first report (let me know if I'm unclear or you have questions).

Test plan: Click each level of breadcrumb on page, ensure they are directed to proper page (all the way back to Home)

(PASS) Home > Abilities
(PASS) Home > Abilities > Strength
(N/A ) Home > Abilities > Strength > Attack (Melee) <--redirect--> Home > Combat > Action > Attack (Melee)
(N/A ) Home > Abilities > Strength > Attack (Ranged) <--redirect--> Home > Combat > Action > Attack (Ranged)
(PASS) Home > Abilities > Strength > Athletics
(PASS) Home > Abilities > Strength > Carry Capacity
(N/A ) Home > Abilities > Strength > Jump <--redirect--> Home > Movement > Jump
(PASS) Home > Abilities > Strength > Push, Drag, Lift
(PASS) Home > Abilities > Dexterity
(PASS) Home > Abilities > Dexterity > Acrobatics
(N/A ) Home > Abilities > Dexterity > Attack (Melee) <--redirect--> Home > Combat > Action > Attack (Melee)
(N/A ) Home > Abilities > Dexterity > Attack (Ranged) <--redirect--> Home > Combat > Action > Attack (Ranged)
(PASS) Home > Abilities > Dexterity > Armor Class
(PASS) Home > Abilities > Dexterity > Hiding
(PASS) Home > Abilities > Dexterity > Initiative
(PASS) Home > Abilities > Dexterity > Sleight of Hand
(PASS) Home > Abilities > Dexterity > Stealth
(PASS) Home > Abilities > Constitution
(**FAIL**) Home > Abilities > Constitution > Hit Dice (see notes below)
(PASS) Home > Abilities > Constitution > Hit Points
(N/A ) Home > Abilities > Constitution > Hold Breath <--redirect--> Home > Life & Death > Suffocating
(PASS) Home > Abilities > Intelligence
(PASS) Home > Abilities > Intelligence > Arcana
(PASS) Home > Abilities > Intelligence > History
(PASS) Home > Abilities > Intelligence > Nature
(PASS) Home > Abilities > Intelligence > Religion
(N/A ) Home > Abilities > Intelligence > Spell Attack <--redirect--> Home > Spellcasting > Spell Ability
(N/A ) Home > Abilities > Intelligence > Spell Save DC <--redirect--> Home > Spellcasting > Spell Save DC
(PASS) Home > Abilities > Wisdom
(**FAIL**) Home > Abilities > Wisdom > Animal Handling (see notes below)
(PASS) Home > Abilities > Wisdom > Insight
(PASS) Home > Abilities > Wisdom > Medicine
(PASS) Home > Abilities > Wisdom > Perception
(N/A ) Home > Abilities > Wisdom > Spell Attack <--redirect--> Home > Spellcasting > Spell Ability
(N/A ) Home > Abilities > Wisdom > Spell Save DC <--redirect--> Home > Spellcasting > Spell Save DC
(PASS) Home > Abilities > Wisdom > Survival
(PASS) Home > Abilities > Charisma
(PASS) Home > Abilities > Charisma > Deception
(PASS) Home > Abilities > Charisma > Intimidation
(PASS) Home > Abilities > Charisma > Performance
(PASS) Home > Abilities > Charisma > Persuasion
(N/A ) Home > Abilities > Charisma > Spell Attack <--redirect--> Home > Spellcasting > Spell Ability
(N/A ) Home > Abilities > Charisma > Spell Save DC <--redirect--> Home > Spellcasting > Spell Save DC
(PASS) Home > Abilities > Ability Checks
(PASS) Home > Abilities > Ability Modifiers
(PASS) Home > Abilities > Alternate Abilities
(PASS) Home > Abilities > Advantage & Disadvantage
(PASS) Home > Abilities > Contests
(PASS) Home > Abilities > Difficulty Class
(PASS) Home > Abilities > Group Checks
(PASS) Home > Abilities > Passive Checks
(PASS) Home > Abilities > Saving Throws
(PASS) Home > Abilities > Working Together

Notes:
1. The last breadcrumb on Home > Abilities > Constitution > Hit Dice, reads "Hit Points" instead of "Hit Dice". Page content is fine. 
2. The breadcrumb to Home > Abilities > Wisdom > Animal Handling is missing the "Wisdom" breadcrumb. Page content is fine.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Campaign

**Comment by TheCrazySpy** [comment]
(PASS) Home > Character
(FAIL) Home > Characters > Advancement
(FAIL) Home > Characters > Class Features
(FAIL) Home > Characters > Class Features > Extra Attack
(FAIL) Home > Characters > Class Features > Sneak Attack
(FAIL) Home > Characters > Class Features > Wild Shape
(FAIL) Home > Characters > Custom Origin
(FAIL) Home > Characters > Determine Ability Scores
(FAIL) Home > Characters > Height & Weight
( ?? ) Home > Characters > Language
(FAIL) Home > Characters > Multiclassing
(FAIL) Home > Characters > Multiclassing > Class Features
(FAIL) Home > Characters > Multiclassing > Prerequisites
(FAIL) Home > Characters > Multiclassing > Proficiencies
(FAIL) Home > Characters > Multiclassing > Spellcasting
(FAIL) Home > Characters > Proficiency Bonus
(FAIL) Home > Characters > Starting Wealth

Notes:
1. The "Characters" breadcrumb on Home > Characters > Advancement doesn't go anywhere. The "Home" breadcumb works.
2. The "Characters" breadcrumb on Home > Characters > Class Features doesn't go anywhere. The "Home" breadcumb works.
3. The "Characters" and "Class Features" breadcrumbs on Home > Characters > Class Features > Extra Attack don't go anywhere. The "Home" breadcumb works.
4. The "Characters" and "Class Features" breadcrumbs on Home > Characters > Class Features > Sneak Attack don't go anywhere. The "Home" breadcumb works.
5. The "Characters" and "Class Features" breadcrumbs on Home > Characters > Class Features > Wild Shape don't go anywhere. The "Home" breadcumb works.
6. The "Characters" breadcrumb on Home > Characters > Custom Origin doesn't go anywhere. The "Home" breadcumb works.
7. The "Characters" breadcrumb on Home > Characters > Determine Ability Scores doesn't go anywhere. The "Home" breadcumb works.
8. The "Characters" breadcrumb on Home > Characters > Height & Weight doesn't go anywhere. The "Home" breadcumb works.
9. The Home > Characters > Language page is missing
10. The "Characters" breadcrumb on Home > Characters > Multiclassing doesn't go anywhere. The "Home" breadcumb works.
11. The "Characters" breadcrumb on Home > Characters > Multiclassing > Class Features doesn't go anywhere. The "Multiclassing" and "Home" breadcumbs work.
12. The "Characters" breadcrumb on Home > Characters > Multiclassing > Prerequisites doesn't go anywhere. The "Multiclassing" and "Home" breadcumbs work.
13. The "Characters" breadcrumb on Home > Characters > Multiclassing > Proficiencies doesn't go anywhere. The "Multiclassing" and "Home" breadcumbs work.
14. The "Characters" breadcrumb on Home > Characters > Multiclassing > Spellcasting doesn't go anywhere. The "Multiclassing" and "Home" breadcumbs work.
15. The "Characters" breadcrumb on Home > Characters > Proficiency Bonus doesn't go anywhere. The "Home" breadcumb works.
16. The "Characters" breadcrumb on Home > Characters > Starting Wealth doesn't go anywhere. The "Home" breadcumb works.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Combat
(**FAIL**) Home > Combat > Action
(**FAIL**) Home > Combat > Action > Attack (Melee)
(**FAIL**) Home > Combat > Action > Attack (Ranged)
(**FAIL**) Home > Combat > Action > Cast Spell
(**FAIL**) Home > Combat > Action > Dash
(**FAIL**) Home > Combat > Action > Disengage
(**FAIL**) Home > Combat > Action > Dodge
(**FAIL**) Home > Combat > Action > Help
(**FAIL**) Home > Combat > Action > Hide
(**FAIL**) Home > Combat > Action > Ready
(**FAIL**) Home > Combat > Action > Search
(**FAIL**) Home > Combat > Action > Use Object
(**FAIL**) Home > Combat > Bonus Action
(**FAIL**) Home > Combat > Cover
(**FAIL**) Home > Combat > Critical Hit & Miss
(**FAIL**) Home > Combat > Damage Type
(**FAIL**) Home > Combat > Flanking
(**FAIL**) Home > Combat > Free Action
(**FAIL**) Home > Combat > Grapple & Shove
(**FAIL**) Home > Combat > Improvised Weapon
(**FAIL**) Home > Combat > Mounted Combat
(**FAIL**) Home > Combat > Nonlethal Damage
(**FAIL**) Home > Combat > Object AC & [HP](hit-points)
(**FAIL**) Home > Combat > Opportunity Attack
(**FAIL**) Home > Combat > Reaction
(**FAIL**) Home > Combat > Resistance & Vulnrability
(**FAIL**) Home > Combat > Two Weapon Fighting
(**FAIL**) Home > Combat > Unarmed Strike
(**FAIL**) Home > Combat > Underwater Combat
(**FAIL**) Home > Combat > Unseen Attacker

Notes:
1. The "Combat" breadcrumb on Home > Combat > Action doesn't go anywhere. The "Home" breadcumb works.
2. The "Combat" breadcrumb on Home > Combat > Action > Attack (Melee) doesn't go anywhere. The "Action" and "Home" breadcumbs works.
3. The "Combat" breadcrumb on Home > Combat > Action > Attack (Ranged) doesn't go anywhere. The "Action" and "Home" breadcumbs works.
4. The "Combat" breadcrumb on Home > Combat > Action > Cast Spell doesn't go anywhere. The "Action" and "Home" breadcumbs works.
5. The "Combat" breadcrumb on Home > Combat > Action > Dash doesn't go anywhere. The "Action" and "Home" breadcumbs works.
6. The "Combat" breadcrumb on Home > Combat > Action > Disengage doesn't go anywhere. The "Action" and "Home" breadcumbs works.
7. The "Combat" breadcrumb on Home > Combat > Action > Dodge doesn't go anywhere. The "Action" and "Home" breadcumbs works.
8. The "Combat" breadcrumb on Home > Combat > Action > Help doesn't go anywhere. The "Action" and "Home" breadcumbs works.
9. The "Combat" breadcrumb on Home > Combat > Action > Hide doesn't go anywhere. The "Action" and "Home" breadcumbs works.
10. The "Combat" breadcrumb on Home > Combat > Action > Ready doesn't go anywhere. The "Action" and "Home" breadcumbs works.
11. The "Combat" breadcrumb on Home > Combat > Action > Search doesn't go anywhere. The "Action" and "Home" breadcumbs works.
12. The "Combat" breadcrumb on Home > Combat > Action > Use Object doesn't go anywhere. The "Action" and "Home" breadcumbs works.
13. The "Combat" breadcrumb on Home > Combat > Bonus Action doesn't go anywhere. The "Home" breadcumb works.
14. The "Combat" breadcrumb on Home > Combat > Cover doesn't go anywhere. The "Home" breadcumb works.
15. The "Combat" breadcrumb on Home > Combat > Critical Hit & Miss doesn't go anywhere. The "Home" breadcumb works.
16. The "Combat" breadcrumb on Home > Combat > Damage Type doesn't go anywhere. The "Home" breadcumb works.
17. The "Combat" breadcrumb on Home > Combat > Flanking doesn't go anywhere. The "Home" breadcumb works.
18. The "Combat" breadcrumb on Home > Combat > Free Action doesn't go anywhere. The "Home" breadcumb works.
19. The "Combat" breadcrumb on Home > Combat > Grappple & Shove doesn't go anywhere. The "Home" breadcumb works.
20. The "Combat" breadcrumb on Home > Combat > Improvised Weapon doesn't go anywhere. The "Home" breadcumb works.
21. The "Combat" breadcrumb on Home > Combat > Mounted Combat doesn't go anywhere. The "Home" breadcumb works.
22. The "Combat" breadcrumb on Home > Combat > Nonlethal Damage doesn't go anywhere. The "Home" breadcumb works.
23. "Home > Combat > Object AC & [HP](hit-points)" button is labeled incorrectly and doesn't go anywhere. Should be named "Object AC & HP" and link the Object AC & HP page. The page contains the breadcrumb Home > Combat > Object AC & HP, the "Combat" breadcrumb doesn't go anywhere. The "Home" breadcumb works.
24. The "Combat" breadcrumb on Home > Combat > Opportunity Attack doesn't go anywhere. The "Home" breadcumb works.
25. "Home > Combat > Reaction" links to the proper page, but the breadcrumbs are Home > Combat > Actions in Combat > Reaction (extra "Actions in Combat" breadcrumb). The Combat breadcrumb doesn't work, but the "Home" breadcumb works.
26. The "Combat" breadcrumb on Home > Combat > Resistance & Vulnrability doesn't go anywhere. The "Home" breadcumb works.
27. The "Combat" breadcrumb on Home > Combat > Two Weapon Fighting doesn't go anywhere. The "Home" breadcumb works.
28. The "Combat" breadcrumb on Home > Combat > Unarmed Strike doesn't go anywhere. The "Home" breadcumb works.
29. The "Combat" breadcrumb on Home > Combat > Underwater Combat doesn't go anywhere. The "Home" breadcumb works.
30. The "Combat" breadcrumb on Home > Combat > Unseen Attacker doesn't go anywhere. The "Home" breadcumb works.

**Comment by MrFarland** [comment]
This has been super helpful, thank you. The moral of the story is ... when you decide to change naming conventions and use global search/replace to make those changes, bad things will happen.

**Comment by MrFarland** [comment]
And, I spotted a trend that will affect others, so I'd hold off on testing any more for a few hours.

**Comment by MrFarland** [comment]
Yep, about 181 additional breadcrumb typos all related to a file reorg I made weeks ago. They should all work now.

**Comment by TheCrazySpy** [comment]
Fantastic, I'll pull down the changes and take a look a little later today.

**Comment by TheCrazySpy** [comment]
(**FAIL**) Home > Characters > Class Features > Sneak Attack

Notes:
1. The "Class Features" breadcrumb on Home > Characters > Class Features > Sneak Attack doesn't go anywhere. All other breadcrumbs work.
2. Realized group is named "Character" but breadcrumb is "Characters" (with an "s") on all pages.

Confirmed all other reported issue have been fixed.

**Comment by TheCrazySpy** [comment]
Confirm reported "Abilities" bugs have been fixed.

**Comment by TheCrazySpy** [comment]
Confirmed reported "Combat" bugs have been fixed.

**Comment by MrFarland** [comment]
Not sure why I didn't fix Sneak Attack and Wild Shape when I fixed Extra Attack.

**Comment by TheCrazySpy** [comment]
That's why another pair of eyes is always good to have! 😉

**Comment by MrFarland** [comment]
I'm going to start checking all content links on the pages in abilities.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Conditions
(PASS) Home > Conditions > Blinded
(PASS) Home > Conditions > Charmed
(PASS) Home > Conditions > Cursed
(PASS) Home > Conditions > Deafened
(PASS) Home > Conditions > Diseased
(PASS) Home > Conditions > Exhaustion
(PASS) Home > Conditions > Frightened
(PASS) Home > Conditions > Grappled
(PASS) Home > Conditions > Incapacitated
(PASS) Home > Conditions > Invisible
(PASS) Home > Conditions > Madness
(PASS) Home > Conditions > Madness > Short Term Madness _(see notes)_
(PASS) Home > Conditions > Madness > Long Term _(see notes)_
(PASS) Home > Conditions > Madness > Indefinite _(see notes)_
(PASS) Home > Conditions > Paralyzed
(PASS) Home > Conditions > Petrified
(PASS) Home > Conditions > Poisoned
(PASS) Home > Conditions > Prone
(PASS) Home > Conditions > Restrained
(PASS) Home > Conditions > Stunned
(PASS) Home > Conditions > Surprised
(PASS) Home > Conditions > Unconscious

Notes:
1. Page name consistency: Short term madness page title is "Short Term Madness", however long term and indefinite madness pages are missing "Madness" from their title and last breadcrumb. Breadcrumbs links work fine.
2. Short term, long term and indefinite madness buttons don't include "Madness", which doesn't match the page name for Short Term Madness. Thus far, all button names have matched page names, but this may have been an intentional ommission.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Downtime
(PASS) Home > Downtime > Brew Healing Potion
(PASS) Home > Downtime > Build Stronghold
(PASS) Home > Downtime > Buy Magic Item
(PASS) Home > Downtime > Carousing
(PASS) Home > Downtime > Craft Item
(PASS) Home > Downtime > Craft Magical Item
(PASS) Home > Downtime > Crime
(PASS) Home > Downtime > Gain Renown
(PASS) Home > Downtime > Gambling
(PASS) Home > Downtime > Pit Fighting
(PASS) Home > Downtime > Relaxing
(PASS) Home > Downtime > Religious Service
(PASS) Home > Downtime > Research
(PASS) Home > Downtime > Scribe Scroll
(PASS) Home > Downtime > Sow Rumor
(PASS) Home > Downtime > Train
(PASS) Home > Downtime > Work

**Comment by MrFarland** [comment]
Yes, the madness was by design to prevent the breadcrumb from wrapping. Seemed repititive in the breadcrumb, but the pages need to include it to insure they come up when searching for madness.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Encounters
(PASS) Home > Encounters > Encounter Generator
(PASS) Home > Encounters > Puzzles
(PASS) Home > Encounters > Puzzles > Creature Painting
(**Fail**) Home > Encounters > Puzzles > Reckless Steps
(PASS) Home > Encounters > Puzzles > Skeleton Keys
(PASS) Home > Encounters > Puzzles > All That Glitters
(PASS) Home > Encounters > Puzzles > Eye of the Beholder
(PASS) Home > Encounters > Puzzles > Four by Four
(PASS) Home > Encounters > Puzzles > Illusive Island
(PASS) Home > Encounters > Puzzles > Material Components
(PASS) Home > Encounters > Puzzles > Members Only
(PASS) Home > Encounters > Puzzles > Exact Change
(PASS) Home > Encounters > Puzzles > Four Elements
(PASS) Home > Encounters > Puzzles > Haunted Hallway
(PASS) Home > Encounters > Puzzles > What’s on the Menu
(PASS) Home > Encounters > Trap Generator

Notes:
1. Home > Encounters > Puzzles > Reckless Steps button link doesn't take you to "Reckless Steps" page. Reckless Steps page exists, all breadcrumbs work on it.

**Comment by MrFarland** [comment]
Supposed to be Restless. Oops

**Comment by TheCrazySpy** [comment]
(PASS) Home > Environment
(PASS) Home > Environment > Desecrated Ground
(PASS) Home > Environment > Eldritch Mist
(**NOTE**) Home > Environment > Eldritch Mist > Ghost 1-2 (see notes) (_see notes_)
(**NOTE**) Home > Environment > Eldritch Mist > Shadowfell 3-4 (see notes) (_see notes_)
(**NOTE**) Home > Environment > Eldritch Mist > Wild Magic 5-6 (see notes) (_see notes_)
(PASS) Home > Environment > Encounter Distance
(PASS) Home > Environment > Falling
(PASS) Home > Environment > Falling > Falling in Water
(PASS) Home > Environment > Falling > Falling on Creature
(PASS) Home > Environment > Falling > Flying & Falling
(PASS) Home > Environment > Falling > Rate of Falling
(PASS) Home > Environment > Improvised Damage
(PASS) Home > Environment > Light & Vision
(PASS) Home > Environment > Light & Vision > Blindsight
(PASS) Home > Environment > Light & Vision > Darkvision
(PASS) Home > Environment > Light & Vision > Light Sources
(PASS) Home > Environment > Light & Vision > Heavily Obscured
(PASS) Home > Environment > Light & Vision > Lightly Obscured
(PASS) Home > Environment > Light & Vision > Truesight
(PASS) Home > Environment > Magical Phenomena
(PASS) Home > Environment > Magical Phenomena > Eldritch Storm
(PASS) Home > Environment > Magical Phenomena > Emotional Echo
(PASS) Home > Environment > Magical Phenomena > Enchanted Spring
(PASS) Home > Environment > Magical Phenomena > Magic Mushroom
(PASS) Home > Environment > Magical Phenomena > Mimic Colony
(PASS) Home > Environment > Magical Phenomena > Primal Fruit
(PASS) Home > Environment > Magical Phenomena > Unearthly Road
(**FAIL**) Home > Environment > Magical Storms 
(PASS) Home > Environment > Spells as Hazards
(PASS) Home > Environment > Supernatural Regions
(PASS) Home > Environment > Supernatural Regions > Blessed Radiance
(PASS) Home > Environment > Supernatural Regions > Far Realm
(PASS) Home > Environment > Supernatural Regions > Haunted
(PASS) Home > Environment > Supernatural Regions > Infested
(PASS) Home > Environment > Supernatural Regions > Mirror Zone
(PASS) Home > Environment > Supernatural Regions > Psychic Resonance
(PASS) Home > Environment > Supernatural Regions > Unraveling Magic
(PASS) Home > Environment > Tracking
(PASS) Home > Environment > Water Hazards
(PASS) Home > Environment > Water Hazards > Blue Hole
(PASS) Home > Environment > Water Hazards > Coral Reef
(PASS) Home > Environment > Water Hazards > Current
(PASS) Home > Environment > Water Hazards > Depth
(PASS) Home > Environment > Water Hazards > Frigid Water
(PASS) Home > Environment > Water Hazards > Slippery Ice
(PASS) Home > Environment > Water Hazards > Thin Ice
(PASS) Home > Environment > Water Hazards > Kelp Forest
(PASS) Home > Environment > Water Hazards > Kraken’s Grave
(PASS) Home > Environment > Water Hazards > Lure Lights
(PASS) Home > Environment > Water Hazards > Sandbar
(PASS) Home > Environment > Water Hazards > Sapping Snow
(PASS) Home > Environment > Water Hazards > Whirlpool
(PASS) Home > Environment > Wilderness Hazards
(PASS) Home > Environment > Wilderness Hazards > Avalanche & Rock Slide
(PASS) Home > Environment > Wilderness Hazards > High Altitude
(PASS) Home > Environment > Wilderness Hazards > Quicksand
(PASS) Home > Environment > Wilderness Hazards > Razorvine

Notes:
1. Eldritch Mist (Ghost), Eldritch Mist (Shadowfell), and Eldritch Mist (Wild Magic) pages missing breadcrumb back to Home > Environment > Eldritch Mist. Buttons on Eldritch Mist page take you to the proper pages, and the breadcrumbs that do exist on the pages work.
2. Home > Environment > Magical Storms button doesn't link to anything. Didn't find a "Magical Storms" page in the Environment group.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Equipment
(PASS) Home > Equipment > Adventuring Gear
(PASS) Home > Equipment > Armor
(PASS) Home > Equipment > Containers & Capacity
(PASS) Home > Equipment > Explosives
(PASS) Home > Equipment > Firearms (button name "Firearms (Gunslinger)")
(**FAIL**) Home > Equipment > Mount & Tack
(PASS) Home > Equipment > Musical Instruments
(PASS) Home > Equipment > Poisons
(PASS) Home > Equipment > Tools
(PASS) Home > Equipment > Weapon Properties
(PASS) Home > Equipment > Weapons

Notes:
1. Home > Equipment > Mount & Tack button doesn't link to a page. Didn't find a "Mount & Tack" page in the Equipement group.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Expenses
(PASS) Home > Expenses > Store Generator
(PASS) Home > Expenses > Inn & Tavern Generator
(PASS) Home > Expenses > Exchange Rates
(PASS) Home > Expenses > Food & Drink
(PASS) Home > Expenses > Lifestyle
(PASS) Home > Expenses > Lodging
(PASS) Home > Expenses > Mounts & Tack
(PASS) Home > Expenses > Services
(PASS) Home > Expenses > Spellcasting Services
(PASS) Home > Expenses > Upkeep
(PASS) Home > Expenses > Vehicles

**Comment by MrFarland** [comment]
Lots of mistakes in spell casting. working on those now.

**Comment by MrFarland** [comment]
Good lord, I think I did this section drunk.

**Comment by TheCrazySpy** [comment]
LOL, I haven't reached that section yet. I'll hold off after Movement and wait for changes before proceeding.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Life & Death
(PASS) Home > Life & Death > Death Saving Throws
(PASS) Home > Life & Death > Food & Water
(PASS) Home > Life & Death > Foraging
(PASS) Home > Life & Death > Healing
(PASS) Home > Life & Death > Instant Death
(PASS) Home > Life & Death > Long Rest
(PASS) Home > Life & Death > Short Rest
(PASS) Home > Life & Death > Resurrection
(PASS) Home > Life & Death > Sleep
(PASS) Home > Life & Death > Stabilizing
(PASS) Home > Life & Death > Suffocating
(PASS) Home > Life & Death > Temporary Hit Points

**Comment by TheCrazySpy** [comment]
(**NOTE**) Home > Movement
(PASS) Home > Movement > Climb
(PASS) Home > Movement > Crawl
(PASS) Home > Movement > Difficult Terrain
(PASS) Home > Movement > Forced March
(PASS) Home > Movement > Jump
(**NOTE**) Home > Movement > Swim
(PASS) Home > Movement > Travel Pace

Notes:
1. Home > Movement button named "Movement" but breadcrumb is "Home > Movement & Travel". Breadcrumb to "Home" works. Subpages have the properly named breadcrumb "Movement".
2. Noticed the table on Home > Movement > Swim uses the color green, all other tables found so far have been gray.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Treasure
(PASS) Home > Treasure > Book Generator
(PASS) Home > Treasure > Loot Generator
(PASS) Home > Treasure > Treasure Generator
(PASS) Home > Treasure > Magic Item Generator
(PASS) Home > Treasure > Magic Item Tables
(PASS) Home > Treasure > Spellbook Generator

**Comment by MrFarland** [comment]
OK. I fixed a lot of issues. I also changed up the encounter, treasure, and world building pages to remove the generators that do not yet work. They're still there, just hidden. The menus and breadcrumbs should all be fixed now and I just finished checking every single content link. (Lot of tapping). 

Thank you for your help. You saved me a lot of time. Let me know if you find any other typos.

**Comment by TheCrazySpy** [comment]
(PASS) Home > Worldbuilding
(**FAIL**) Home > Worldbuilding > Group Patron
(PASS) Home > Worldbuilding > Location Generator
(PASS) Home > Worldbuilding > Name Generator
(PASS) Home > Worldbuilding > Plot Hooks
(PASS) Home > Worldbuilding > Rival
(PASS) Home > Worldbuilding > Villain
(**FAIL**) Home > Worldbuilding > World Shaking Event
(**NOTE**) Home > worldbuilding > Group Patrons
(PASS) Home > Worldbuilding > Group Patrons > Academy
(PASS) Home > Worldbuilding > Group Patrons > Ancient Being
(PASS) Home > Worldbuilding > Group Patrons > Aristocrat
(PASS) Home > Worldbuilding > Group Patrons > Criminal Syndicate
(PASS) Home > Worldbuilding > Group Patrons > Guild
(PASS) Home > Worldbuilding > Group Patrons > Military Force
(PASS) Home > Worldbuilding > Group Patrons > Religious Order
(PASS) Home > Worldbuilding > Group Patrons > Sovereign

Note:
1. Home > Worldbuilding > Group Patron button doesn't link to a page. Found "Group Patrons" (with an "s") page in Worldbuilding group. See "Home > Worldbuilding > Group Patrons" (with an "s") on status.
2. Home > Worldbuilding > World Shaking Event button doesn't link to a page. Found "World-Shaking Events" page in Worldbuilding group. Breadcrumbs work on this page. "World-Shaking Events" page uses the color green on the table.
3. The "Worldbuilding" breadcrumb in Home > worldbuilding > Group Patrons has a lowercase "w". Breadcrumbs work though.
4. Need button link to Home > Worldbuilding > NPC Generator
5. Need button link to Home > Worldbuilding > Settlement Generator

**Comment by TheCrazySpy** [comment]
> OK. I fixed a lot of issues. I also changed up the encounter, treasure, and world building pages to remove the generators that do not yet work. They're still there, just hidden. The menus and breadcrumbs should all be fixed now and I just finished checking every single content link. (Lot of tapping).
> 
> Thank you for your help. You saved me a lot of time. Let me know if you find any other typos.

Oh oops, just finished checking the Worldbuilding section before your changes. I also skipped Spellcasting as you mentioned you had work to do there. Aside from these, I've finished my first test pass. I can validate the changes you made once I pull them. 

I haven't really paid too much attention to the actual content. I did offhandedly notice where formatting needs to be updated on a few pages. I can circle back and make notes on those if you want to open a new issue to validate formatting.

I could make changes and submit pull requests, but I also know this is your thing, built based on how you run your games. I wouldn't want to step on your toes. 

And you're welcome for the help. I'll admit I have a selfish reason to help, I want the DM screen. 😁

**Comment by MrFarland** [comment]
I'll probably step back and come back to it tomorrow, so feel free to do your thing. Everything is as up-to-date as it will get today.

Formatting is a tough one. I want it to look good when launched from the "Shortcut" bar as it is the most commonly used for quick lookups. This screen can be resized and will look different on different sized devices.  

I will create an issue for a content check, BUT I'm not sure I want to dive too deep. Every time I do, I come up with a new way to do things and end up taking two steps back only to discover the 1st way was better. Hence so many broken breadcrumbs.

Long term, the goal is to create a module that people can fork and tinker with to their heart's content. They can add, remove, change content all they want. GitHub and Module Packer really make that easy for those not afraid to give it a shot.
