### ISSUE TITLE
Perform a Random Content Audit of all Sections.

### ISSUE THREAD

**Issue by MrFarland** [MrFarland/DM-Operations-Center#52]
Perform a random content audit of about 10-20% of the pages in each section to look for spelling mistakes, nonsensical language, and other formatting issues.

- [x] Abilities
- [x] Campaign
- [x] Character
- [x] Combat
- [x] Conditions
- [x] Downtime
- [x] Encounters
- [x] Environment
- [x] Equipment
- [x] Expenses
- [x] Life & Death
- [x] Movement
- [x] Spellcasting
- [x] Treasure
- [x] Worldbuilding

**Comment by TheCrazySpy** [comment]
I can help find existing text formatting issues like spelling, space between certain characters, missing characters, table color (so they all match, there's a couple of green ones), spelling, grammar, etc. You maintain the content and how it's laid out. I'm not looking to change the actual content. As time permits, I just want to help you reach your goal!

I've forked to go through the code (I'm halfway through abilities already). I can submit a pull request after I've finished, and you can choose whether to pull it or not. 

If you're not interested in this, let me know, and I'll remain hands-off.

**Comment by MrFarland** [comment]
That most definitely works for me.

**Comment by TheCrazySpy** [comment]
No changes needed for Campaign page.

**Comment by MrFarland** [comment]
All good changes.

**Comment by TheCrazySpy** [comment]
I will work on the remaining tasks this weekend.

**Comment by TheCrazySpy** [comment]
Proofing/editing should be complete.

**Comment by MrFarland** [comment]
Thank you do much for your help. This whole week I'm getting my daughter packed and move into her dorm and have been flat out. You've saved me a ton of work and time.

**Comment by TheCrazySpy** [comment]
You bet! If I see anything else I can help out with, I'll be happy to contribute some more.
