### ISSUE TITLE
Update the "XXX" references to the SRD where I didn't have time to look them up.

### ISSUE THREAD

**Issue by MrFarland** [MrFarland/DM-Operations-Center#53]
A number of pages have references to the Player's Handbook and System Reference Document where the page number is "xxx". I need to look these up and find the correct page for their reference.

- [x] Class Features - Wild Shape
- [x] Armor
- [x] Containers & Capacity
- [x] Food and Drink
- [x] Lifestyle
- [x] Lodging
- [x] Difficult Terrain

**Comment by TheCrazySpy** [comment]
Based on SRD-OGL v5.1

Class Features - Wild Shape:
Player’s Handbook, p. 66-67

Armor:
System Reference Document, p. 63

Containers & Capacity
System Reference Document, p. 69-70

Food and Drink:
System Reference Document, p. 73-74
Dungeons & Dragons versus Rick & Morty, p. XXX (I don't own this adventure)

Lifestyle:
System Reference Document, p. 72-73

Lodging:
System Reference Document, p. 73-74

Difficult Terrain:
System Reference Document, p. 85, 91
