### ISSUE TITLE
Create "dev" branch for volatile JS development.

### ISSUE THREAD

**Issue by MrFarland** [MrFarland/DM-Operations-Center#71]
I am creating this issue as an umbrella for any issues I run into related to the creation and management of a new "dev" branch. As someone relatively new to using Git, I suspect I'll run into some issues here and there related to managing and merging branches.

Comment if you see any issues related to my management of the branches while I'm learning.

**Comment by TheCrazySpy** [comment]
Merge issues may only become an issue if more than one developer is working on the same code. As long as each person maintains their working copy though, merge conflicts shouldn't exist.
